unit TestuClasseVenda;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, uClasseVenda;

type
  // Test methods for class TVendaClass

  TestTVendaClass = class(TTestCase)
  strict private
    FVendaClass: TVendaClass;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestInsereVenda;
  end;

implementation

procedure TestTVendaClass.SetUp;
begin
  FVendaClass := TVendaClass.Create;
end;

procedure TestTVendaClass.TearDown;
begin
  FVendaClass.Free;
  FVendaClass := nil;
end;

procedure TestTVendaClass.TestInsereVenda;
begin
  FVendaClass.ValorLitro      := 5.49;
  FVendaClass.TipoCombustivel := 'Gasolina';
  FVendaClass.Imposto         := FVendaClass.ValorLitro * 0.15;
  FVendaClass.Litro           := 1;
  FVendaClass.DataVenda       := 2023-05-29;
  FVendaClass.ValorTotal      := (FVendaClass.ValorLitro + FVendaClass.Imposto) * FVendaClass.Litro;
  FVendaClass.IDBomba         := 5;
  FVendaClass.DeletaTeste     := True;
  FVendaClass.DeletaVenda;

  FVendaClass.InsereVenda;

  Assert(FVendaClass.VerificaInsertTeste);
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTVendaClass.Suite);
end.

