--
-- File generated with SQLiteStudio v3.3.3 on seg mai 29 01:00:12 2023
--
-- Text encoding used: System
--
PRAGMA foreign_keys = off;
BEGIN TRANSACTION;

-- Table: BOMBA
CREATE TABLE BOMBA (ID INTEGER PRIMARY KEY AUTOINCREMENT, NOME STRING (1, 25) NOT NULL, TIPOCOMBUSTIVEL STRING (1, 8) NOT NULL, VALORLITRO NUMERIC (10, 2) NOT NULL);
INSERT INTO BOMBA (ID, NOME, TIPOCOMBUSTIVEL, VALORLITRO) VALUES (5, 'BOMBAGASOL2', 'Gasolina', 5.49);
INSERT INTO BOMBA (ID, NOME, TIPOCOMBUSTIVEL, VALORLITRO) VALUES (6, 'BOMBAGASOL1', 'Gasolina', 5.59);
INSERT INTO BOMBA (ID, NOME, TIPOCOMBUSTIVEL, VALORLITRO) VALUES (7, 'BOMBADIESEL1', 'Diesel', 7);
INSERT INTO BOMBA (ID, NOME, TIPOCOMBUSTIVEL, VALORLITRO) VALUES (8, 'BOMBADIESEL2', 'Diesel', 8.5);

-- Table: CADASTRO
CREATE TABLE CADASTRO (ID INTEGER PRIMARY KEY AUTOINCREMENT, NOMEPOSTO STRING (1, 25) NOT NULL, CNPJ BIGINT NOT NULL);
INSERT INTO CADASTRO (ID, NOMEPOSTO, CNPJ) VALUES (1, 'teste', 12315615615615);

-- Table: TANQUE
CREATE TABLE TANQUE (ID INTEGER PRIMARY KEY AUTOINCREMENT, NOME STRING (1, 25) NOT NULL, TIPOCOMBUSTIVEL STRING (1, 8) NOT NULL, ESTOQUE INTEGER NOT NULL);
INSERT INTO TANQUE (ID, NOME, TIPOCOMBUSTIVEL, ESTOQUE) VALUES (1, 'TANQUEGASOL', 'Gasolina', 0);
INSERT INTO TANQUE (ID, NOME, TIPOCOMBUSTIVEL, ESTOQUE) VALUES (4, 'TANQUEDIESEL', 'Diesel', 979);

-- Table: VENDA
CREATE TABLE VENDA (ID INTEGER PRIMARY KEY AUTOINCREMENT, VALORLITRO NUMERIC (10, 2) NOT NULL, TIPOCOMBUSTIVEL STRING (1, 8) NOT NULL, IMPOSTO NUMERIC (10, 2) NOT NULL, LITRO INTEGER NOT NULL, DATAVENDA DATETIME NOT NULL, VALORTOTAL NUMERIC (10, 2) NOT NULL, IDBOMBA INTEGER NOT NULL);
INSERT INTO VENDA (ID, VALORLITRO, TIPOCOMBUSTIVEL, IMPOSTO, LITRO, DATAVENDA, VALORTOTAL, IDBOMBA) VALUES (30, 5.49, 'Gasolina', 0.8235, 5, '2023-05-29', 31.5675, 5);
INSERT INTO VENDA (ID, VALORLITRO, TIPOCOMBUSTIVEL, IMPOSTO, LITRO, DATAVENDA, VALORTOTAL, IDBOMBA) VALUES (31, 8.5, 'Diesel', 1.275, 1, '2023-05-29', 9.775, 8);

COMMIT TRANSACTION;
PRAGMA foreign_keys = on;
